# Generated by Django 3.0.6 on 2020-06-01 00:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('uri', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('title', models.CharField(default='', max_length=512)),
                ('summary', models.TextField(default='')),
                ('date', models.DateField(db_index=True)),
                ('images', models.TextField(default='')),
                ('is_promoted', models.BooleanField(db_index=True, default=False)),
                ('article_count', models.PositiveIntegerField(db_index=True)),
                ('sentiment', models.FloatField(blank=True, null=True)),
                ('wgt', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Medium',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('uri', models.CharField(db_index=True, max_length=128)),
                ('favicon', models.URLField(blank=True, max_length=512, null=True)),
                ('slant', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Far left'), (2, 'Liberal'), (3, 'Conservative'), (4, 'Far right')], null=True)),
                ('is_embeddable', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('uri', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('title', models.CharField(default='', max_length=512)),
                ('content', models.TextField(default='')),
                ('url', models.URLField(max_length=512)),
                ('datetime', models.DateTimeField()),
                ('image', models.CharField(blank=True, max_length=512, null=True)),
                ('sentiment', models.FloatField(blank=True, null=True)),
                ('sentimentRNN', models.FloatField(blank=True, null=True)),
                ('og_title', models.CharField(blank=True, max_length=512, null=True)),
                ('og_image', models.CharField(blank=True, max_length=512, null=True)),
                ('og_description', models.CharField(blank=True, max_length=512, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='news.Event')),
                ('medium', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='news.Medium')),
            ],
        ),
    ]
