# Generated by Django 2.2.4 on 2019-08-12 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=512)),
                ('summary', models.TextField(default='')),
                ('uri', models.CharField(db_index=True, max_length=128)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Medium',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('uri', models.CharField(db_index=True, max_length=128)),
                ('slant', models.CharField(blank=True, choices=[('left', 'far left'), ('lib', 'liberal'), ('con', 'conservative'), ('right', 'far right')], max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=512)),
                ('content', models.TextField(default='')),
                ('url', models.URLField(max_length=512)),
                ('datetime', models.DateTimeField()),
                ('uri', models.CharField(db_index=True, max_length=128)),
                ('image', models.CharField(max_length=512)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='news.Event')),
                ('medium', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='news.Medium')),
            ],
        ),
    ]
