# Generated by Django 3.0.6 on 2020-06-11 05:27

import constants
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-article_count']},
        ),
        migrations.AddField(
            model_name='medium',
            name='reliability',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='medium',
            name='slant',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(constants.Orientations['FAR_LEFT'], 'Far left'), (constants.Orientations['LIBERAL'], 'Liberal'), (constants.Orientations['CONSERVATIVE'], 'Conservative'), (constants.Orientations['FAR_RIGHT'], 'Far right')], null=True),
        ),
    ]
