# Generated by Django 3.0.6 on 2020-06-12 09:59

import constants
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('news', '0002_auto_20200611_0527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medium',
            name='slant',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(constants.Orientations['LEFT'], 'Left'),
                                                                        (constants.Orientations['NEUTRAL'], 'Neutral'),
                                                                        (constants.Orientations['RIGHT'], 'Right')],
                                                   null=True),
        ),
    ]
