# Generated by Django 2.2.4 on 2019-08-13 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20190813_0946'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='sentiment',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
