# Generated by Django 3.0.6 on 2020-06-12 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('news', '0003_auto_20200612_0959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='articles',
                                    to='news.Event'),
        ),
    ]
