# Generated by Django 2.2.4 on 2019-08-20 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_event_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='medium',
            name='favicon',
            field=models.URLField(blank=True, max_length=512, null=True),
        ),
    ]
