# Generated by Django 2.2.4 on 2019-08-21 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_article_sentimentrnn'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='og_description',
            field=models.CharField(default='', max_length=512),
        ),
        migrations.AddField(
            model_name='article',
            name='og_image',
            field=models.CharField(default='', max_length=512),
        ),
        migrations.AddField(
            model_name='article',
            name='og_title',
            field=models.CharField(default='', max_length=512),
        ),
    ]
