# Generated by Django 2.2.4 on 2019-08-21 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_auto_20190821_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='og_description',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='og_image',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='og_title',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
