# Generated by Django 2.2.4 on 2019-08-26 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_auto_20190821_1337'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='is_hidden',
            new_name='is_visible',
        ),
    ]
