# Generated by Django 2.2.4 on 2020-05-16 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0010_auto_20190826_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medium',
            name='slant',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Far left'), (2, 'Liberal'), (3, 'Conservative'), (4, 'Far right')], null=True),
        ),
    ]
